NAME = rush-02

PATH = ./srcs/

SRC = $(PATH)convert_dict.c $(PATH)ft_char_atoi.c $(PATH)ft_split.c $(PATH)main.c $(PATH)parse_conditions.c $(PATH)utilitaries.c $(PATH)words_list.c

all:
	gcc -Wall -Wextra -Werror -I ./includes $(SRC) -o $(NAME)

fclean:
	rm -rf rush-02 $(NAME)
